### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by psenechal** [jonataslaw/get_storage#33]
Can't seem to figure this one out. I don't have any problems launching this on an iOS simulator, but launching on either an Android API 29 or API 30 simulator causes the following error and a blank screen. If I comment out await GetStorage.init(); in my code, the app launches, although without storage capabilities. Any ideas on what might be going wrong?

STACK TRACE
```
E/flutter ( 8379): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 8379): #0      GetStorage._init (package:get_storage/src/storage_impl.dart:47:7)
E/flutter ( 8379): <asynchronous suspension>
E/flutter ( 8379): #1      new GetStorage._internal.<anonymous closure> (package:get_storage/src/storage_impl.dart:27:13)
E/flutter ( 8379): #2      new Future.<anonymous closure> (dart:async/future.dart:175:37)
E/flutter ( 8379): #3      _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 8379): #4      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 8379): #5      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 8379): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 8379): #7      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 8379): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 8379): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter ( 8379): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter ( 8379): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter ( 8379): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter ( 8379): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

pubspec.yaml
```
name: got_brix
description: Winemakers Management & Cellar Tracking Tool

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 0.14.3
  crypto: 2.1.5
  cupertino_icons: 1.0.0
  firebase_analytics: 6.2.0
  firebase_auth: 0.18.3
  firebase_core: 0.5.2
  flutter_facebook_auth: 1.0.0+3
  flutter_svg: 0.19.1
  font_awesome_flutter: '>= 4.7.0'
  get: 3.17.1
  get_storage: 1.3.2
  google_sign_in: 4.5.6
  sign_in_with_apple: 2.5.4
  video_player: 1.0.0

dependency_overrides:
  font_awesome_flutter:
    path: '../font_awesome_flutter'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
```

I tried adding path_provider as a dependency (yes, did a clean and pub get and rebooted several times) and nothing changed

I'm on Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale en-US)

Any suggestions are greatly appreciated. Thanks!
