### ISSUE TITLE
Cannot build on Flutter 2.0

### ISSUE THREAD

**Issue by luis-cruzt** [jonataslaw/get_storage#44]
I'm migrating my app to the new Flutter version, but i'm getting the following error:

`get_storage ^1.4.0 which depends on path_provider ^1.6.22, path_provider ^1.6.22 is required. So, because example_app depends on path_provider ^2.0.1, version solving failed`

@jonataslaw

**Comment by ahmaddarwesh** [comment]
Until package update to support `path_provider 2`, You can use `dependency_overrides` like this :

```
dependencies:
  get_storage: ^1.4.0
  ...

dependency_overrides:
  path_provider: ^2.0.1
```

That's worked for me
